DROP DATABASE IF EXISTS notesDB;
CREATE DATABASE notesDB;

USE notesDB;

CREATE TABLE notes(
  id INT NOT NULL AUTO_INCREMENT,
  note_title VARCHAR(10) NOT NULL,
  note_text_area VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);